// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: proto/bus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vec2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_bus_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GpsLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawLoc *Vec2 `protobuf:"bytes,1,opt,name=raw_loc,json=rawLoc,proto3" json:"raw_loc,omitempty"`
	AdjLoc *Vec2 `protobuf:"bytes,2,opt,name=adj_loc,json=adjLoc,proto3" json:"adj_loc,omitempty"`
}

func (x *GpsLocation) Reset() {
	*x = GpsLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GpsLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsLocation) ProtoMessage() {}

func (x *GpsLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsLocation.ProtoReflect.Descriptor instead.
func (*GpsLocation) Descriptor() ([]byte, []int) {
	return file_proto_bus_proto_rawDescGZIP(), []int{1}
}

func (x *GpsLocation) GetRawLoc() *Vec2 {
	if x != nil {
		return x.RawLoc
	}
	return nil
}

func (x *GpsLocation) GetAdjLoc() *Vec2 {
	if x != nil {
		return x.AdjLoc
	}
	return nil
}

type Bus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trace []*Vec2 `protobuf:"bytes,1,rep,name=trace,proto3" json:"trace,omitempty"`
}

func (x *Bus) Reset() {
	*x = Bus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bus) ProtoMessage() {}

func (x *Bus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bus.ProtoReflect.Descriptor instead.
func (*Bus) Descriptor() ([]byte, []int) {
	return file_proto_bus_proto_rawDescGZIP(), []int{2}
}

func (x *Bus) GetTrace() []*Vec2 {
	if x != nil {
		return x.Trace
	}
	return nil
}

var File_proto_bus_proto protoreflect.FileDescriptor

var file_proto_bus_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x22, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x4d, 0x0a, 0x0b, 0x47, 0x70, 0x73, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x07, 0x72, 0x61, 0x77, 0x5f, 0x6c, 0x6f, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x56, 0x65, 0x63, 0x32, 0x52, 0x06, 0x72, 0x61,
	0x77, 0x4c, 0x6f, 0x63, 0x12, 0x1e, 0x0a, 0x07, 0x61, 0x64, 0x6a, 0x5f, 0x6c, 0x6f, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x56, 0x65, 0x63, 0x32, 0x52, 0x06, 0x61, 0x64,
	0x6a, 0x4c, 0x6f, 0x63, 0x22, 0x22, 0x0a, 0x03, 0x42, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x56, 0x65, 0x63,
	0x32, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bus_proto_rawDescOnce sync.Once
	file_proto_bus_proto_rawDescData = file_proto_bus_proto_rawDesc
)

func file_proto_bus_proto_rawDescGZIP() []byte {
	file_proto_bus_proto_rawDescOnce.Do(func() {
		file_proto_bus_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bus_proto_rawDescData)
	})
	return file_proto_bus_proto_rawDescData
}

var file_proto_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_bus_proto_goTypes = []interface{}{
	(*Vec2)(nil),        // 0: Vec2
	(*GpsLocation)(nil), // 1: GpsLocation
	(*Bus)(nil),         // 2: Bus
}
var file_proto_bus_proto_depIdxs = []int32{
	0, // 0: GpsLocation.raw_loc:type_name -> Vec2
	0, // 1: GpsLocation.adj_loc:type_name -> Vec2
	0, // 2: Bus.trace:type_name -> Vec2
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_bus_proto_init() }
func file_proto_bus_proto_init() {
	if File_proto_bus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GpsLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bus_proto_goTypes,
		DependencyIndexes: file_proto_bus_proto_depIdxs,
		MessageInfos:      file_proto_bus_proto_msgTypes,
	}.Build()
	File_proto_bus_proto = out.File
	file_proto_bus_proto_rawDesc = nil
	file_proto_bus_proto_goTypes = nil
	file_proto_bus_proto_depIdxs = nil
}
